Yap
workflows:
  android-build:
    name: Android APK Build
    max_build_duration: 30
    environment:
      flutter: stable
    scripts:
      - name: Setup Android platform
        script: flutter create --platforms=android .
      - name: Pub get packages
        script: flutter pub get
      - name: Build release APK
        script: flutter build apk --release --no-pub
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
