workflows:
  android-build:
    name: Android APK Build
    instance_type: mac_mini_m1
    max_build_duration: 30
    scripts:
      - name: Get dependencies
        script: flutter packages pub get
      - name: Build APK
        script: flutter build apk --release --no-pub
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
